### ISSUE TITLE
Internal state of open mixed up

### ISSUE THREAD

**Issue by SantoJambit** [tuxor1337/hidetopbar#202]
I got this the second time now, so I thought I'd write a report:
When the bug happens, the show/hide logic is messed up. For example: 
- When I move the mouse to the top of the screen:
  - normal: it shows the top bar (animate in)
  - buggy: nothing happens
- When I press the super key
  - normal: it shows the top bar (animate in)
  - buggy: the top bar is instantly visible and then gets hidden (animate out)

So my assumption is, that at this point in time, the apps internal state says open, while it's actually not open and it says not open while it's actually open and instead of saying "show" or "hide", it just says "toggle".

I am not sure how to reproduce. Disabling the extension does not fix it => the top bar stays hidden. I need to restart the pc to fix this.

Ubuntu 18.04.

**Comment by yut23** [comment]
I've just experienced this issue, and figured out how to reproduce it: enable the extension then immediately disable it.
```
gnome-extensions enable hidetopbar@mathieu.bidon.ca; gnome-extensions disable hidetopbar@mathieu.bidon.ca
```
This causes an error in `_bindUIChanges` (and then a bunch of similar errors whenever the overlay is opened):
```
JS ERROR: Error: Argument 'settings' (type interface) may not be null
addKeybinding@resource:///org/gnome/shell/ui/windowManager.js:1270:22
_bindUIChanges@.../hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:380:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```
This implies a race condition with the timeout in the PanelVisibilityManager constructor: https://github.com/mlutfy/hidetopbar/blob/15ef0e545bc882a28897957439e9b17cbbfb4df5/panelVisibilityManager.js#L66
I have submitted a PR that should fix it.

**Comment by tuxor1337** [comment]
Thanks, @yut23 !

**Comment by SantoJambit** [comment]
I usually don't enable/disable the extension. It happens seemingly at random times. I will report back if it still happens.

**Comment by SantoJambit** [comment]
Tomorrow morning I upgraded the extension to the latest available version. A couple of hours later it happened again, so it's not fixed.

**Comment by tuxor1337** [comment]
Closing as fixed by #356
